/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.ti;

import classes.Coordenador;
import conexao.Conecta;
import java.sql.Connection;
import repositorio.Inserir;

/**
 *
 * @author igor_
 */
public class TelaCadastro extends javax.swing.JFrame {

    boolean professor = false;
    boolean visivel = false;
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
        
       txtDisciplina.setVisible(false);
        campoDisciplina.setVisible(false);
        visivelCadastroCoordenador(true);
        visivelCadastroAcesso(false);
        
   
        
    }
       public static void visivelCadastroCoordenador(boolean b){
      //campos
      campoNome.setVisible(b);
      campoSalario.setVisible(b);
      ComboBoxTurno.setVisible(b);
      CheckBoxProfessor.setVisible(b);
      buttonCadastrar.setVisible(b);
      
      //nomes
      txtNome.setVisible(b);
      txtSalario.setVisible(b);
      txtTurno.setVisible(b);
      txtProfessor.setVisible(b);
      imgCoordenador.setVisible(b);
      }
       public static void visivelCadastroAcesso(boolean b){
        //campos
       campoLogin.setVisible(b);
       campoSenha.setVisible(b);
       comboBoxCoordenador.setVisible(b);
       comboBoxProfessor.setVisible(b);
       ComboBoxFuncionario.setVisible(b);
       ButtonCadastrarAcesso.setVisible(b);
       
       //nomes
       
       txtLogin.setVisible(b);
       txtSenha.setVisible(b);
       txtCoordenadorAcesso.setVisible(b);
       txtProfessorAcesso.setVisible(b);
       txtFuncionarioAcesso.setVisible(b);
       
       }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipoCadastro = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        txtTurno = new javax.swing.JLabel();
        ComboBoxTurno = new javax.swing.JComboBox<>();
        campoSalario = new javax.swing.JTextField();
        txtSalario = new javax.swing.JLabel();
        txtProfessor = new javax.swing.JLabel();
        CheckBoxProfessor = new javax.swing.JCheckBox();
        campoDisciplina = new javax.swing.JTextField();
        txtDisciplina = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JButton();
        imgCoordenador = new javax.swing.JLabel();
        tipoCadastro = new javax.swing.JLabel();
        RadioCoordenador = new javax.swing.JRadioButton();
        RadioAcesso = new javax.swing.JRadioButton();
        txtLogin = new javax.swing.JLabel();
        campoLogin = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JLabel();
        comboBoxProfessor = new javax.swing.JComboBox<>();
        txtProfessorAcesso = new javax.swing.JLabel();
        comboBoxCoordenador = new javax.swing.JComboBox<>();
        txtCoordenadorAcesso = new javax.swing.JLabel();
        txtFuncionarioAcesso = new javax.swing.JLabel();
        ComboBoxFuncionario = new javax.swing.JComboBox<>();
        ButtonCadastrarAcesso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1366, 710));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconleft.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 30, 100, 60);

        txtNome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNome.setText("Nome:");
        getContentPane().add(txtNome);
        txtNome.setBounds(580, 200, 90, 40);

        campoNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(campoNome);
        campoNome.setBounds(580, 250, 320, 30);

        txtTurno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTurno.setText("Turno:");
        getContentPane().add(txtTurno);
        txtTurno.setBounds(580, 320, 80, 29);

        ComboBoxTurno.setEditable(true);
        ComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Diurno", "Noturno", "Integral" }));
        ComboBoxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxTurno);
        ComboBoxTurno.setBounds(670, 320, 230, 30);
        getContentPane().add(campoSalario);
        campoSalario.setBounds(670, 410, 90, 30);

        txtSalario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSalario.setText("Salário:");
        getContentPane().add(txtSalario);
        txtSalario.setBounds(580, 410, 81, 30);

        txtProfessor.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtProfessor.setText("Professor:");
        getContentPane().add(txtProfessor);
        txtProfessor.setBounds(780, 410, 109, 30);

        CheckBoxProfessor.setContentAreaFilled(false);
        CheckBoxProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(CheckBoxProfessor);
        CheckBoxProfessor.setBounds(890, 410, 20, 30);
        getContentPane().add(campoDisciplina);
        campoDisciplina.setBounds(580, 550, 320, 30);

        txtDisciplina.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtDisciplina.setText("Disciplina:");
        getContentPane().add(txtDisciplina);
        txtDisciplina.setBounds(580, 500, 110, 29);

        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonCadastrar);
        buttonCadastrar.setBounds(670, 610, 160, 30);

        imgCoordenador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconcoordenador.png"))); // NOI18N
        getContentPane().add(imgCoordenador);
        imgCoordenador.setBounds(190, 330, 260, 290);

        tipoCadastro.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        tipoCadastro.setText("Tipo de cadastro:");
        getContentPane().add(tipoCadastro);
        tipoCadastro.setBounds(140, 210, 190, 30);

        grupoTipoCadastro.add(RadioCoordenador);
        RadioCoordenador.setText("Coordenador");
        RadioCoordenador.setContentAreaFilled(false);
        RadioCoordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCoordenadorActionPerformed(evt);
            }
        });
        getContentPane().add(RadioCoordenador);
        RadioCoordenador.setBounds(340, 220, 100, 23);

        grupoTipoCadastro.add(RadioAcesso);
        RadioAcesso.setText("Acesso");
        RadioAcesso.setContentAreaFilled(false);
        RadioAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioAcessoActionPerformed(evt);
            }
        });
        getContentPane().add(RadioAcesso);
        RadioAcesso.setBounds(450, 220, 80, 23);

        txtLogin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtLogin.setText("Login:");
        getContentPane().add(txtLogin);
        txtLogin.setBounds(970, 200, 70, 30);
        getContentPane().add(campoLogin);
        campoLogin.setBounds(970, 250, 320, 30);
        getContentPane().add(campoSenha);
        campoSenha.setBounds(970, 370, 320, 30);

        txtSenha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSenha.setText("Senha:");
        getContentPane().add(txtSenha);
        txtSenha.setBounds(970, 320, 80, 30);

        comboBoxProfessor.setEditable(true);
        comboBoxProfessor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBoxProfessor);
        comboBoxProfessor.setBounds(1140, 460, 150, 30);

        txtProfessorAcesso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtProfessorAcesso.setText("Professor:");
        getContentPane().add(txtProfessorAcesso);
        txtProfessorAcesso.setBounds(970, 460, 110, 30);

        comboBoxCoordenador.setEditable(true);
        comboBoxCoordenador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(comboBoxCoordenador);
        comboBoxCoordenador.setBounds(1140, 530, 150, 30);

        txtCoordenadorAcesso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtCoordenadorAcesso.setText("Coordenador:");
        getContentPane().add(txtCoordenadorAcesso);
        txtCoordenadorAcesso.setBounds(970, 530, 150, 30);

        txtFuncionarioAcesso.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFuncionarioAcesso.setText("Funcionario:");
        getContentPane().add(txtFuncionarioAcesso);
        txtFuncionarioAcesso.setBounds(970, 590, 140, 40);

        ComboBoxFuncionario.setEditable(true);
        ComboBoxFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboBoxFuncionario);
        ComboBoxFuncionario.setBounds(1140, 600, 150, 30);

        ButtonCadastrarAcesso.setText("Cadastrar");
        getContentPane().add(ButtonCadastrarAcesso);
        ButtonCadastrarAcesso.setBounds(1060, 650, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaLimpa.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 750);

        setSize(new java.awt.Dimension(1382, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBoxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTurnoActionPerformed

    private void CheckBoxProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxProfessorActionPerformed
        // TODO add your handling code here:
           
                   if(CheckBoxProfessor.isSelected()){
        
        txtDisciplina.setVisible(true);
       campoDisciplina.setVisible(true);
       this.professor = true;
                   }
                   if(CheckBoxProfessor.isSelected()==false){
                   txtDisciplina.setVisible(false);
       campoDisciplina.setVisible(false);
       this.professor = false;
                   }
                   
    }//GEN-LAST:event_CheckBoxProfessorActionPerformed

    private void RadioAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioAcessoActionPerformed
        // TODO add your handling code here:
        
        if(RadioAcesso.isSelected())
        {
            visivelCadastroCoordenador(false);
            visivelCadastroAcesso(true);
        
        }
    }//GEN-LAST:event_RadioAcessoActionPerformed

    private void RadioCoordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCoordenadorActionPerformed
        // TODO add your handling code here:
        if(RadioCoordenador.isSelected()){
            visivelCadastroCoordenador(true);
            visivelCadastroAcesso(false);
        }
        
             
        
    }//GEN-LAST:event_RadioCoordenadorActionPerformed

    private void buttonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarActionPerformed
        // TODO add your handling code here:
        Conecta con = new Conecta();
        Connection conexao= con.Conecta();
        
        boolean professor = false;
        String nome = campoNome.getText();
        String turno = (String)ComboBoxTurno.getSelectedItem();
        double salario = Double.parseDouble(campoSalario.getText());
        if(CheckBoxProfessor.isSelected()){
        professor = true;
        }
        Coordenador c = new Coordenador(nome, turno, salario, professor,true);
       
        Inserir.inserirCoordenador(c, conexao);
    }//GEN-LAST:event_buttonCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
           //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
        
            }
        });
        
          
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ButtonCadastrarAcesso;
    public static javax.swing.JCheckBox CheckBoxProfessor;
    public static javax.swing.JComboBox<String> ComboBoxFuncionario;
    public static javax.swing.JComboBox<String> ComboBoxTurno;
    public static javax.swing.JRadioButton RadioAcesso;
    public static javax.swing.JRadioButton RadioCoordenador;
    public static javax.swing.JButton buttonCadastrar;
    public static javax.swing.JTextField campoDisciplina;
    public static javax.swing.JTextField campoLogin;
    public static javax.swing.JTextField campoNome;
    public static javax.swing.JTextField campoSalario;
    public static javax.swing.JPasswordField campoSenha;
    public static javax.swing.JComboBox<String> comboBoxCoordenador;
    public static javax.swing.JComboBox<String> comboBoxProfessor;
    public static javax.swing.ButtonGroup grupoTipoCadastro;
    public static javax.swing.JLabel imgCoordenador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel tipoCadastro;
    public static javax.swing.JLabel txtCoordenadorAcesso;
    public static javax.swing.JLabel txtDisciplina;
    public static javax.swing.JLabel txtFuncionarioAcesso;
    public static javax.swing.JLabel txtLogin;
    public static javax.swing.JLabel txtNome;
    public static javax.swing.JLabel txtProfessor;
    public static javax.swing.JLabel txtProfessorAcesso;
    public static javax.swing.JLabel txtSalario;
    public static javax.swing.JLabel txtSenha;
    public static javax.swing.JLabel txtTurno;
    // End of variables declaration//GEN-END:variables
}
