/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.coordenador;

import classes.Coordenador;
import classes.Professor;
import java.sql.*;
import conexao.Conecta;
import repositorio.Inserir;
import repositorio.pilha.Pilha;


/**
 *
 * @author J.Anderson
 */
public class TelaCadastrar extends javax.swing.JFrame {
    
  Conecta con = new Conecta();
  Connection conexao = con.Conecta();
  int idcoordenador;     
    
    
    /**
     * Creates new form TelaCadastrar
     */
    public TelaCadastrar() {
        initComponents();
        
      
        Coordenador c = Pilha.tirarCoordenador();
       this.idcoordenador = c.getIdcoordenador();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoFormacao = new javax.swing.JTextField();
        campoSalario = new javax.swing.JTextField();
        txtNome = new javax.swing.JLabel();
        txtTurno = new javax.swing.JLabel();
        txtSalario = new javax.swing.JLabel();
        txtFormacao = new javax.swing.JLabel();
        txtNome3 = new javax.swing.JLabel();
        ComboBoxTurno = new javax.swing.JComboBox();
        Cadastrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 710));
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconleft.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 10, 90, 60);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cadastro Professor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(510, 20, 440, 50);
        getContentPane().add(campoNome);
        campoNome.setBounds(520, 190, 320, 30);

        campoFormacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoFormacaoActionPerformed(evt);
            }
        });
        getContentPane().add(campoFormacao);
        campoFormacao.setBounds(520, 280, 320, 30);
        getContentPane().add(campoSalario);
        campoSalario.setBounds(620, 430, 220, 30);

        txtNome.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNome.setText("Nome:");
        getContentPane().add(txtNome);
        txtNome.setBounds(520, 150, 70, 30);

        txtTurno.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtTurno.setText("Turno:");
        getContentPane().add(txtTurno);
        txtTurno.setBounds(520, 340, 130, 30);

        txtSalario.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSalario.setText("Salario: ");
        getContentPane().add(txtSalario);
        txtSalario.setBounds(520, 430, 160, 30);

        txtFormacao.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtFormacao.setText("Formação:");
        getContentPane().add(txtFormacao);
        txtFormacao.setBounds(520, 240, 150, 30);

        txtNome3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtNome3.setText("Nome");
        getContentPane().add(txtNome3);
        txtNome3.setBounds(520, 150, 70, 30);

        ComboBoxTurno.setEditable(true);
        ComboBoxTurno.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diurno", "Noturno", "Integral" }));
        ComboBoxTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTurnoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboBoxTurno);
        ComboBoxTurno.setBounds(610, 340, 230, 30);

        Cadastrar.setText("Cadastrar ");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar);
        Cadastrar.setBounds(600, 550, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/TelaLimpa.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1390, 710);

        setSize(new java.awt.Dimension(1382, 749));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void campoFormacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoFormacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoFormacaoActionPerformed

    private void ComboBoxTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTurnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTurnoActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        // TODO add your handling code here:
        String nome = campoNome.getText();
        Double salario = Double.parseDouble(campoSalario.getText());
        String formacao = campoFormacao.getText();
        String turno = (String)ComboBoxTurno.getSelectedItem();
        int coordenador = this.idcoordenador;
        
        Professor p = new Professor(nome, turno, salario, formacao, coordenador,0,true);
        Inserir.inserirProfessor(p, conexao);
        this.dispose();
        
  //  String nome, String turno, double salario, String formacao, int coordenador_idcoordenador,  int nota_avaliacao,boolean status
    }//GEN-LAST:event_CadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JComboBox ComboBoxTurno;
    private javax.swing.JTextField campoFormacao;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtFormacao;
    private javax.swing.JLabel txtNome;
    private javax.swing.JLabel txtNome3;
    private javax.swing.JLabel txtSalario;
    private javax.swing.JLabel txtTurno;
    // End of variables declaration//GEN-END:variables
}
