/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import classes.Acesso;
import classes.Coordenador;
import classes.Departamento;
import classes.Funcionario;
import classes.Professor;
import conexao.Conecta;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import repositorio.pilha.AcessoPilha;
import repositorio.pilha.Pilha;
import views.coordenador.TelaCadastrar;
import views.coordenador.TelaPrincipalCoordenador;
import views.professor.TelaPrincipal;
import views.ti.TelaPrincipalTi;

/**
 *
 * @author igor_
 */
public class TelaLogin extends javax.swing.JFrame {

    Conecta con = new Conecta();
    Connection conexao;
    Connection conex;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();

        conexao = con.Conecta();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        acesso = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        campoLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RadioProfessor = new javax.swing.JRadioButton();
        RadioCoordenador = new javax.swing.JRadioButton();
        RadioTi = new javax.swing.JRadioButton();
        campoSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(255, 153, 0));
        jToggleButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jToggleButton1.setText("Login");
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(680, 510, 190, 30);

        campoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(campoLogin);
        campoLogin.setBounds(630, 330, 280, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 390, 130, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logofavip.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 80, 800, 310);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(630, 300, 80, 20);

        RadioProfessor.setBackground(new java.awt.Color(3, 54, 130));
        acesso.add(RadioProfessor);
        RadioProfessor.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        RadioProfessor.setForeground(new java.awt.Color(255, 255, 255));
        RadioProfessor.setText("Professor");
        RadioProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(RadioProfessor);
        RadioProfessor.setBounds(660, 460, 80, 21);

        RadioCoordenador.setBackground(new java.awt.Color(3, 54, 130));
        acesso.add(RadioCoordenador);
        RadioCoordenador.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        RadioCoordenador.setForeground(new java.awt.Color(255, 255, 255));
        RadioCoordenador.setText("Coordenador");
        RadioCoordenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCoordenadorActionPerformed(evt);
            }
        });
        getContentPane().add(RadioCoordenador);
        RadioCoordenador.setBounds(740, 460, 87, 21);

        RadioTi.setBackground(new java.awt.Color(3, 54, 130));
        acesso.add(RadioTi);
        RadioTi.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        RadioTi.setForeground(new java.awt.Color(255, 255, 255));
        RadioTi.setText("TI");
        RadioTi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTiActionPerformed(evt);
            }
        });
        getContentPane().add(RadioTi);
        RadioTi.setBounds(830, 460, 93, 21);
        getContentPane().add(campoSenha);
        campoSenha.setBounds(630, 420, 280, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaLogin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1370, 768);

        setSize(new java.awt.Dimension(1382, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

        String sql = "SELECT * FROM ACESSO WHERE LOGIN ='" + campoLogin.getText() + "'";
        try {
            PreparedStatement stmt = conexao.prepareStatement(sql);
            ResultSet rst = stmt.executeQuery();

            while (rst.next()) {
                if (rst.getString("senha") == campoSenha.getText() && rst.getBoolean("Status") == true);
                {
                     System.out.println("logado");

                    if (RadioCoordenador.isSelected()) {

                        int cod = rst.getInt("coordenador_idcoordenador");
                        String query = "SELECT * FROM COORDENADOR WHERE IDCOORDENADOR='" + cod + "'";
                        PreparedStatement Cstmt = conexao.prepareStatement(query);
                        ResultSet Crst = Cstmt.executeQuery();

                        while (Crst.next()) {

                            if (Crst.getBoolean("status") == true) {
                                Coordenador c = new Coordenador(Crst.getString("nome"), Crst.getString("turno"), Crst.getDouble("salario"), Crst.getBoolean("professor"), Crst.getBoolean("status"),Crst.getInt("idcoordenador"));

                                Acesso a = new Acesso(rst.getString("login"), rst.getInt("idacesso"), rst.getString("senha"));

                                AcessoPilha.acessoPilha(a);

                                
                                Pilha.coordenadorPilha(c);
                                TelaCadastrar tpc = new TelaCadastrar();
                                tpc.setVisible(true);
                                this.dispose();
                            } else {

                                JOptionPane.showMessageDialog(null, "User inválido");
                            }

                        }

                    } 
                }
                if (RadioProfessor.isSelected()) {

                    int cod = rst.getInt("professor_idprofessor");
                    String query = "SELECT * FROM PROFESSOR WHERE IDPROFESSOR='" + cod + "'";
                    PreparedStatement Pstmt = conexao.prepareStatement(query);
                    ResultSet Prst = Pstmt.executeQuery();

                    while (Prst.next()) {

                        if (Prst.getBoolean("status") == true) {
                            Professor p = new Professor(Prst.getString("nome"), Prst.getString("turno"), Prst.getDouble("salario"), Prst.getString("formacao"), Prst.getInt("coordenador_idcoordenador"), Prst.getInt("nota_avaliacao"), Prst.getBoolean("status"));

                            Acesso a = new Acesso(rst.getString("login"), rst.getInt("idacesso"), rst.getString("senha"));

                            AcessoPilha.acessoPilha(a);

                            
                            Pilha.professorPilha(p);
                            TelaPrincipal tp = new TelaPrincipal();
                            tp.setVisible(true);
                            this.dispose();

                        }

                    }

                }
                if (RadioTi.isSelected()) {

                    int cod = rst.getInt("funcionario_idfuncionario");
                    String query = "SELECT * FROM FUNCIONARIO WHERE IDFUNCIONARIO='" + cod + "'";
                    PreparedStatement Tstmt = conexao.prepareStatement(query);
                    ResultSet Trst = Tstmt.executeQuery();

                    while (Trst.next()) {

                        if (Trst.getBoolean("status") == true) {
                            Funcionario f = new Funcionario(Trst.getString("cargo"), Trst.getInt("departamento_iddepartamento"), Trst.getString("nome"), Trst.getDouble("salario"), Trst.getBoolean("status"));
                            f.setIdfuncionario(Trst.getInt("idfuncionario"));

                            Acesso a = new Acesso(rst.getString("login"), rst.getInt("idacesso"), rst.getString("senha"));

                            AcessoPilha.acessoPilha(a);

                            Pilha.tiPilha(f);
                            TelaPrincipalTi tpi = new TelaPrincipalTi();
                            tpi.setVisible(true);
                            
                            this.dispose();

                        } else {
                            JOptionPane.showMessageDialog(null, "user inválido");
                        }
                    }

                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void campoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoLoginActionPerformed

    private void RadioProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioProfessorActionPerformed

    private void RadioCoordenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCoordenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCoordenadorActionPerformed

    private void RadioTiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioTiActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioCoordenador;
    private javax.swing.JRadioButton RadioProfessor;
    private javax.swing.JRadioButton RadioTi;
    public static javax.swing.ButtonGroup acesso;
    private javax.swing.JTextField campoLogin;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
